import type { GraphFormatOptions, GraphJsonResult } from "./graph.js";

type GraphJsonModule = GraphJsonResult["modules"][number];
type GraphJsonDrift = NonNullable<GraphJsonResult["drift"]>;

interface MermaidModuleGroup {
  layer?: string;
  modules: GraphJsonModule[];
}

interface MermaidEdge {
  fromModule: string;
  toModule: string;
  importCount: number;
  violationCodes: string[];
  intentionalViolationCodes: string[];
  driftKind?: "new" | "removed";
}

export function formatGraphMermaidFromGraph(
  graph: GraphJsonResult,
  options: GraphFormatOptions = {}
): string {
  const moduleIds = new Map(graph.modules.map((module) => [module.name, mermaidId("module", module.name)]));
  const edges = aggregateMermaidEdges(graph, options);
  const lines = [
    `%% Generated by ${formatMermaidCommandName(options)} --mermaid.`,
    "%% Observed module dependencies are shown; use axi graph --json for the full machine-readable graph.",
    `%% Summary: modules=${graph.summary.modules}, ${formatMermaidObservedDependencySummary(
      graph
    )}, violations=${graph.summary.violations}, intentionalViolations=${graph.summary.intentionalViolations}, warnings=${graph.summary.warnings}.`,
    "%% Warning counts include only advisory checks enabled for this command or config.",
    "flowchart TB"
  ];

  lines.push(...formatMermaidLegend(graph, options));

  const moduleGroups = groupModulesForMermaid(graph.modules);
  if (moduleGroups.length === 0) {
    lines.push("  %% no modules");
  }

  for (const group of moduleGroups) {
    if (group.layer) {
      lines.push(`  subgraph ${mermaidId("layer", group.layer)}["${escapeMermaidLabel(`layer ${group.layer}`)}"]`);
      for (const module of group.modules) {
        lines.push(`    ${readMermaidModuleId(moduleIds, module.name)}["${formatMermaidModuleLabel(module)}"]`);
      }
      lines.push("  end");
    } else {
      for (const module of group.modules) {
        lines.push(`  ${readMermaidModuleId(moduleIds, module.name)}["${formatMermaidModuleLabel(module)}"]`);
      }
    }
  }

  if (options.driftOnly && graph.drift) {
    const knownModules = new Set(graph.modules.map((module) => module.name));
    const driftModules = new Set<string>();
    for (const edge of [...graph.drift.newObservedEdges, ...graph.drift.removedObservedEdges]) {
      driftModules.add(edge.fromModule);
      driftModules.add(edge.toModule);
    }
    const extraModules = [...driftModules].filter((moduleName) => !knownModules.has(moduleName)).sort();
    for (const moduleName of extraModules) {
      lines.push(`  ${readMermaidModuleId(moduleIds, moduleName)}["${escapeMermaidLabel(moduleName)}"]`);
    }
  }

  if (edges.length === 0) {
    lines.push("  %% no observed module dependencies");
  } else {
    for (const edge of edges) {
      const label = formatMermaidEdgeLabel(edge);
      lines.push(
        `  ${readMermaidModuleId(moduleIds, edge.fromModule)} -->|${escapeMermaidEdgeLabel(
          label
        )}| ${readMermaidModuleId(moduleIds, edge.toModule)}`
      );
    }
  }

  return lines.join("\n");
}

function groupModulesForMermaid(modules: GraphJsonModule[]): MermaidModuleGroup[] {
  const groups: MermaidModuleGroup[] = [];
  const indexByLayer = new Map<string, number>();
  const unlayeredModules: GraphJsonModule[] = [];

  for (const module of modules) {
    if (!module.layer) {
      unlayeredModules.push(module);
      continue;
    }

    const groupIndex = indexByLayer.get(module.layer);
    if (groupIndex !== undefined) {
      groups[groupIndex]?.modules.push(module);
      continue;
    }

    indexByLayer.set(module.layer, groups.length);
    groups.push({ layer: module.layer, modules: [module] });
  }

  if (unlayeredModules.length > 0) {
    groups.push({ modules: unlayeredModules });
  }

  return groups;
}

function aggregateMermaidEdges(graph: GraphJsonResult, options: GraphFormatOptions): MermaidEdge[] {
  if (options.driftOnly && graph.drift) {
    return aggregateMermaidDriftEdges(graph.drift);
  }

  const byPair = new Map<string, MermaidEdge>();

  for (const dependency of graph.observedDependencies) {
    const key = `${dependency.fromModule}\0${dependency.toModule}`;
    const edge = byPair.get(key) ?? {
      fromModule: dependency.fromModule,
      toModule: dependency.toModule,
      importCount: 0,
      violationCodes: [],
      intentionalViolationCodes: []
    };

    edge.importCount += 1;
    edge.violationCodes = mergeUnique(edge.violationCodes, dependency.violations.map((violation) => violation.code));
    edge.intentionalViolationCodes = mergeUnique(
      edge.intentionalViolationCodes,
      dependency.intentionalViolations.map((violation) => violation.code)
    );
    byPair.set(key, edge);
  }

  return [...byPair.values()].sort((left, right) =>
    `${left.fromModule}\0${left.toModule}`.localeCompare(`${right.fromModule}\0${right.toModule}`)
  );
}

function aggregateMermaidDriftEdges(drift: GraphJsonDrift): MermaidEdge[] {
  const edges = [
    ...drift.newObservedEdges.map((edge): MermaidEdge => ({
      fromModule: edge.fromModule,
      toModule: edge.toModule,
      importCount: edge.imports.length,
      violationCodes: edge.violations.map((violation) => violation.code),
      intentionalViolationCodes: edge.intentionalViolations.map((violation) => violation.code),
      driftKind: "new"
    })),
    ...drift.removedObservedEdges.map((edge): MermaidEdge => ({
      fromModule: edge.fromModule,
      toModule: edge.toModule,
      importCount: edge.imports.length,
      violationCodes: edge.violations.map((violation) => violation.code),
      intentionalViolationCodes: edge.intentionalViolations.map((violation) => violation.code),
      driftKind: "removed"
    }))
  ];

  return edges.sort((left, right) =>
    `${left.driftKind}\0${left.fromModule}\0${left.toModule}`.localeCompare(
      `${right.driftKind}\0${right.fromModule}\0${right.toModule}`
    )
  );
}

function formatMermaidObservedDependencySummary(graph: GraphJsonResult): string {
  if (!graph.filters.violationsOnly) {
    return `observedDependencies=${graph.summary.observedDependencies}`;
  }

  return `shownDependencyEdges=${graph.summary.shownObservedDependencies}, fullObservedDependencies=${graph.summary.observedDependencies}`;
}

function formatMermaidModuleLabel(module: GraphJsonModule): string {
  const purpose = module.purpose ? `<br/>${escapeMermaidLabel(module.purpose)}` : "";
  return `${escapeMermaidLabel(module.name)}${purpose}`;
}

function formatMermaidEdgeLabel(edge: MermaidEdge): string {
  const parts = [`${edge.importCount} import${pluralize(edge.importCount)}`];
  if (edge.driftKind) {
    parts.push(`${edge.driftKind} edge`);
  }

  const codes = [
    ...edge.violationCodes,
    ...edge.intentionalViolationCodes.map((code) => `${code} intentional`)
  ];

  if (codes.length > 0) {
    parts.push(codes.join(", "));
  }

  return parts.join("; ");
}

function formatMermaidLegend(graph: GraphJsonResult, options: GraphFormatOptions): string[] {
  const viewLabel = options.driftOnly && graph.drift
    ? `Diff view: ${graph.drift.newObservedEdges.length} new, ${graph.drift.removedObservedEdges.length} removed observed module edge${pluralize(
        graph.drift.newObservedEdges.length + graph.drift.removedObservedEdges.length
      )}`
    : graph.filters.violationsOnly
    ? `${options.observe ? "FILTERED observe view" : "FILTERED graph view"}: ${formatObservedDependencyCount(
        graph
      )} observed dependency edges shown`
    : `Full observed view: ${graph.summary.observedDependencies} observed dependency edge${pluralize(
        graph.summary.observedDependencies
      )} shown`;
  const filterLabel = options.driftOnly
    ? "Only baseline drift edges are shown; unchanged edges are omitted"
    : graph.filters.violationsOnly
    ? "Clean observed dependencies are omitted"
    : "Clean and debt edges are both shown";

  return [
    `  subgraph axiom_legend["Axiom graph legend"]`,
    `    axiom_legend_scope["${formatMermaidMultilineLabel([viewLabel, filterLabel])}"]`,
    `    axiom_legend_nodes["${formatMermaidMultilineLabel([
      "Nodes: declared .axi modules",
      "Grouped by declared layer when present"
    ])}"]`,
    `    axiom_legend_edges["${formatMermaidMultilineLabel([
      "Edges: observed imports",
      "Labels show import counts and drift/debt codes"
    ])}"]`,
    `    axiom_legend_output["${formatMermaidMultilineLabel([
      "Presentation output only",
      "Use axi graph --json for machine-readable data",
      "Warnings shown only when checks are enabled"
    ])}"]`,
    "  end"
  ];
}

function formatObservedDependencyCount(graph: GraphJsonResult): string {
  if (!graph.filters.violationsOnly) {
    return String(graph.summary.observedDependencies);
  }

  return `${graph.summary.shownObservedDependencies} of ${graph.summary.observedDependencies}`;
}

function formatMermaidCommandName(options: GraphFormatOptions): string {
  if (options.driftOnly) {
    return "axi diff";
  }

  return options.observe ? "axi observe" : "axi graph";
}

function formatMermaidMultilineLabel(lines: string[]): string {
  return lines.map(escapeMermaidLabel).join("<br/>");
}

function readMermaidModuleId(moduleIds: Map<string, string>, moduleName: string): string {
  const existing = moduleIds.get(moduleName);
  if (existing) {
    return existing;
  }

  const generated = mermaidId("module", moduleName);
  moduleIds.set(moduleName, generated);
  return generated;
}

function mermaidId(prefix: string, value: string): string {
  const normalized = value.replace(/[^A-Za-z0-9_]/g, "_");
  return `${prefix}_${normalized.length > 0 ? normalized : "item"}`;
}

function escapeMermaidLabel(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\r?\n/g, " ");
}

function escapeMermaidEdgeLabel(value: string): string {
  return escapeMermaidLabel(value).replace(/\|/g, "&#124;");
}

function mergeUnique(existing: string[], additions: string[]): string[] {
  return [...new Set([...existing, ...additions])].sort();
}

function pluralize(count: number): string {
  return count === 1 ? "" : "s";
}
