import type { InferResult, InferredDependency, InferredModule } from "../infer/infer.js";

export const inferJsonSchemaVersion = "axiom.infer.v3";

export interface InferJsonResult {
  schemaVersion: typeof inferJsonSchemaVersion;
  root: string;
  starterContract: InferResult["starterContract"];
  summary: {
    sourceFiles: number;
    importsScanned: number;
    candidateModules: number;
    modules: number;
    observedDependencies: number;
    collapsedCycles: number;
  };
  modules: InferredModule[];
  observedDependencies: InferredDependency[];
  collapsedCycles: InferResult["collapsedCycles"];
  axi: string;
}

export function formatInferResult(result: InferResult): string {
  const dependencyEvidence = new Map(
    result.observedDependencies.map((dependency) => [
      dependencyKey(dependency.fromModule, dependency.toModule),
      dependency
    ])
  );
  const lines = [
    "# Generated by axi infer.",
    ...result.starterContract.notice.map((line) => `# ${line}`),
    ""
  ];

  lines.push("# authoring checklist:");
  result.starterContract.authoringChecklist.forEach((item, index) => {
    lines.push(`# ${index + 1}. ${item}`);
  });
  lines.push("");
  lines.push("# next commands:");
  for (const command of result.starterContract.nextCommands) {
    lines.push(`# ${command}`);
  }
  lines.push("");

  for (const cycle of result.collapsedCycles) {
    lines.push(`# collapsed cycle: ${cycle.module}`);
    if (cycle.sourceGroups.length <= 4) {
      lines.push(`# includes: ${cycle.sourceGroups.join(", ")}`);
    } else {
      lines.push("# includes:");
      for (const sourceGroup of cycle.sourceGroups) {
        lines.push(`# - ${sourceGroup}`);
      }
    }
    if (cycle.internalDependencies.length > 0) {
      lines.push("# observed internal edges:");
      for (const dependency of cycle.internalDependencies.slice(0, 8)) {
        lines.push(`# - ${dependency.fromGroup} -> ${dependency.toGroup} (${dependency.count})`);
      }
      if (cycle.internalDependencies.length > 8) {
        lines.push(`# - ... ${cycle.internalDependencies.length - 8} more`);
      }
    }
    lines.push("# reason: inferred groups form a circular dependency, so this starter contract keeps them together.");
    lines.push("# review: rename this merged module after deciding whether the cycle should be split.");
  }

  if (result.collapsedCycles.length > 0) {
    lines.push("");
  }

  for (const module of result.modules) {
    lines.push(`module ${module.name}`);
    for (const pathPattern of module.paths) {
      lines.push(`path "${pathPattern}"`);
    }
    for (const expose of module.suggestedExposes) {
      lines.push(`# suggestion: exposes "${expose}"`);
    }
    for (const hide of module.suggestedHides) {
      lines.push(`# suggestion: hides "${hide}"`);
    }
    for (const dependency of module.depends) {
      const evidence = dependencyEvidence.get(dependencyKey(module.name, dependency));
      if (evidence) {
        lines.push(`# evidence: ${formatImportSiteCount(evidence.count)} observed for ${module.name} -> ${dependency}`);
        const displayedSamples = evidence.samples.slice(0, 3);
        for (const sample of displayedSamples) {
          lines.push(`# sample: ${sample.filePath}:${sample.line} imports "${sample.specifier}" -> ${sample.resolvedPath}`);
        }
        if (displayedSamples.length < evidence.count) {
          lines.push(`# sample: ... ${evidence.count - displayedSamples.length} more observed import sites`);
        }
      }
      lines.push(`depends on ${dependency}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

export function toInferJson(result: InferResult): InferJsonResult {
  return {
    schemaVersion: inferJsonSchemaVersion,
    root: normalizePath(result.root),
    starterContract: result.starterContract,
    summary: {
      sourceFiles: result.sourceFiles.length,
      importsScanned: result.importCount,
      candidateModules: result.candidateModules,
      modules: result.modules.length,
      observedDependencies: result.observedDependencies.length,
      collapsedCycles: result.collapsedCycles.length
    },
    modules: result.modules,
    observedDependencies: result.observedDependencies,
    collapsedCycles: result.collapsedCycles,
    axi: formatInferResult(result)
  };
}

export function formatInferJson(result: InferResult): string {
  return JSON.stringify(toInferJson(result), null, 2);
}

function normalizePath(filePath: string): string {
  return filePath.replace(/\\/g, "/");
}

function dependencyKey(fromModule: string, toModule: string): string {
  return `${fromModule}\0${toModule}`;
}

function formatImportSiteCount(count: number): string {
  return count === 1 ? "1 import site" : `${count} import sites`;
}
