import type { InferResult, InferredDependency, InferredModule } from "../infer/infer.js";

export const inferJsonSchemaVersion = "axiom.infer.v2";

export interface InferJsonResult {
  schemaVersion: typeof inferJsonSchemaVersion;
  root: string;
  starterContract: InferResult["starterContract"];
  summary: {
    sourceFiles: number;
    importsScanned: number;
    candidateModules: number;
    modules: number;
    observedDependencies: number;
    collapsedCycles: number;
  };
  modules: InferredModule[];
  observedDependencies: InferredDependency[];
  collapsedCycles: InferResult["collapsedCycles"];
  axi: string;
}

export function formatInferResult(result: InferResult): string {
  const lines = [
    "# Generated by axi infer.",
    ...result.starterContract.notice.map((line) => `# ${line}`),
    ""
  ];

  for (const cycle of result.collapsedCycles) {
    lines.push(`# collapsed cycle: ${cycle.module}`);
    if (cycle.sourceGroups.length <= 4) {
      lines.push(`# includes: ${cycle.sourceGroups.join(", ")}`);
    } else {
      lines.push("# includes:");
      for (const sourceGroup of cycle.sourceGroups) {
        lines.push(`# - ${sourceGroup}`);
      }
    }
    if (cycle.internalDependencies.length > 0) {
      lines.push("# observed internal edges:");
      for (const dependency of cycle.internalDependencies.slice(0, 8)) {
        lines.push(`# - ${dependency.fromGroup} -> ${dependency.toGroup} (${dependency.count})`);
      }
      if (cycle.internalDependencies.length > 8) {
        lines.push(`# - ... ${cycle.internalDependencies.length - 8} more`);
      }
    }
    lines.push("# reason: inferred groups form a circular dependency, so this starter contract keeps them together.");
    lines.push("# review: rename this merged module after deciding whether the cycle should be split.");
  }

  if (result.collapsedCycles.length > 0) {
    lines.push("");
  }

  for (const module of result.modules) {
    lines.push(`module ${module.name}`);
    for (const pathPattern of module.paths) {
      lines.push(`path "${pathPattern}"`);
    }
    for (const expose of module.suggestedExposes) {
      lines.push(`# suggestion: exposes "${expose}"`);
    }
    for (const hide of module.suggestedHides) {
      lines.push(`# suggestion: hides "${hide}"`);
    }
    for (const dependency of module.depends) {
      lines.push(`depends on ${dependency}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

export function toInferJson(result: InferResult): InferJsonResult {
  return {
    schemaVersion: inferJsonSchemaVersion,
    root: normalizePath(result.root),
    starterContract: result.starterContract,
    summary: {
      sourceFiles: result.sourceFiles.length,
      importsScanned: result.importCount,
      candidateModules: result.candidateModules,
      modules: result.modules.length,
      observedDependencies: result.observedDependencies.length,
      collapsedCycles: result.collapsedCycles.length
    },
    modules: result.modules,
    observedDependencies: result.observedDependencies,
    collapsedCycles: result.collapsedCycles,
    axi: formatInferResult(result)
  };
}

export function formatInferJson(result: InferResult): string {
  return JSON.stringify(toInferJson(result), null, 2);
}

function normalizePath(filePath: string): string {
  return filePath.replace(/\\/g, "/");
}
